# Generated by Django 5.1.4 on 2024-12-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_birth_date_remove_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
